// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIMVC.DbClasses
{
    public partial class ShoppingBag
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }

        public ActivatedAccount ActivatedAccount { get; set; }
        public Product Product { get; set; }

    }
}
